name: color_convert
description: A color conversion library for Dart. It converts all ways between rgb, hsl, hsv, hwb, cmyk, ansi, ansi16, hex strings, and CSS keywords (will round to closest).
version: 2.0.0
repository: https://github.com/crystalboxes/color_convert
homepage: https://github.com/crystalboxes/color_convert

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
